/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufv.visaoGUI.venda;

import br.ufv.controle.ControleProduto;
import br.ufv.controle.ControleVenda;
import br.ufv.modelo.CargoFuncionario;
import br.ufv.modelo.Produto;
import br.ufv.modelo.Venda;
import br.ufv.visaoGUI.funcionario.TelaLogin;
import br.ufv.visaoGUI.funcionario.TelaPrincipalCaixa;
import br.ufv.visaoGUI.funcionario.TelaPrincipalGerente;
import br.ufv.visaoGUI.produto.TelaProduto;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Igorl
 */
public class TelaVenda extends javax.swing.JFrame {

    /**
     * Creates new form TelaCliente
     */
    //private TelaRequestCliente trc;
    private ControleVenda controleVenda;
    private ControleProduto controleProduto;
    private DefaultTableModel model;
    private double precoTot = 0;
    private ArrayList<Produto> pVenda;
    private String idVenda;
    private static boolean visible;
    
    public TelaVenda() {
        initComponents();
        this.setLocationRelativeTo(null);
        controleVenda = new ControleVenda();
        controleProduto = new ControleProduto();
        idVenda = String.valueOf(controleVenda.getIdVenda());
        txtCodVenda.setText(idVenda);
        pVenda = new ArrayList<>();
        visible = true;
        
        model = (DefaultTableModel) tblProdutos.getModel();
    }
    
    
    public void setTableData(Produto p){
        String id = String.valueOf(p.getCodigo());
        String nome = p.getNome();
        String pcUn = String.valueOf(p.getPreco());
        int qtd = Integer.parseInt(spnQtd.getValue().toString());
        String pcTo = String.valueOf(String.format("%.2f", p.getPreco()*qtd));
        
        Object[] row = {id, nome, pcUn, String.valueOf(qtd), pcTo};
        model.addRow(row);
        
    }
    
    public void resetTable(){
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
    }
    
    public static boolean getVisivel(){
        return visible;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblPrecoTot = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txtCodVenda = new javax.swing.JTextField();
        txtCodProduto = new javax.swing.JTextField();
        spnQtd = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btncadastroProd = new javax.swing.JButton();
        btnEditarProd = new javax.swing.JButton();
        btnExcluirProd = new javax.swing.JButton();
        btnListarProd = new javax.swing.JButton();
        btnFinalizarVenda = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProdutos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Preço total:");

        lblPrecoTot.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblPrecoTot.setText("R$ 0.00");

        txtCodVenda.setEditable(false);

        txtCodProduto.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        spnQtd.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        spnQtd.setValue(1);

        jLabel5.setText("Produto");

        jLabel4.setText("Código venda");

        jLabel9.setText("Quantidade");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCodVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCodProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spnQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCodVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtCodProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spnQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(0, 16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPrecoTot)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblPrecoTot))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btncadastroProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/mais.png"))); // NOI18N
        btncadastroProd.setToolTipText("Cadastro");
        btncadastroProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncadastroProdActionPerformed(evt);
            }
        });

        btnEditarProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/lapis.png"))); // NOI18N
        btnEditarProd.setToolTipText("Editar");
        btnEditarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarProdActionPerformed(evt);
            }
        });

        btnExcluirProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/deletar.png"))); // NOI18N
        btnExcluirProd.setToolTipText("Deletar");
        btnExcluirProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirProdActionPerformed(evt);
            }
        });

        btnListarProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisa.png"))); // NOI18N
        btnListarProd.setToolTipText("Listar");
        btnListarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarProdActionPerformed(evt);
            }
        });

        btnFinalizarVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/box.png"))); // NOI18N
        btnFinalizarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarVendaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btncadastroProd, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditarProd, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcluirProd, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnListarProd, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnFinalizarVenda)
                        .addGap(91, 91, 91))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btncadastroProd)
                    .addComponent(btnEditarProd)
                    .addComponent(btnExcluirProd)
                    .addComponent(btnListarProd, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFinalizarVenda)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(23, 0, 255));
        jLabel1.setText("Cadastro de Vendas");

        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/anterior.png"))); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVoltar)
                .addGap(142, 142, 142)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnVoltar)
                    .addComponent(jLabel1))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        tblProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Preço un.", "Qtd", "Preço tot."
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProdutos.getTableHeader().setReorderingAllowed(false);
        tblProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProdutosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProdutos);
        if (tblProdutos.getColumnModel().getColumnCount() > 0) {
            tblProdutos.getColumnModel().getColumn(0).setPreferredWidth(80);
            tblProdutos.getColumnModel().getColumn(1).setPreferredWidth(150);
            tblProdutos.getColumnModel().getColumn(2).setPreferredWidth(100);
            tblProdutos.getColumnModel().getColumn(3).setPreferredWidth(80);
            tblProdutos.getColumnModel().getColumn(4).setPreferredWidth(100);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 30, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        if(TelaLogin.getFuncionarioLogado().getCargo().equals(CargoFuncionario.GERENTE)){
            new TelaPrincipalGerente().setVisible(true);
            this.dispose();
        }else{
            if(TelaLogin.getFuncionarioLogado().getCargo().equals(CargoFuncionario.CAIXA)){
                new TelaPrincipalCaixa().setVisible(true);
                this.dispose();
            }
        }
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btncadastroProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncadastroProdActionPerformed
        Produto p = controleVenda.getProdutoId(Integer.parseInt(txtCodProduto.getText()));
        int qtdProduto = Integer.parseInt(spnQtd.getValue().toString());
        if(!controleProduto.isDisponivel(p, qtdProduto)){
            JOptionPane.showMessageDialog(null, "Sem estoque suficiente!", "Erro",JOptionPane.WARNING_MESSAGE);
            return;
        }
            
        if(p != null){
            this.setTableData(p);
            if(!pVenda.contains(p))
                pVenda.add(p);
            
            precoTot += p.getPreco() * Integer.parseInt(spnQtd.getValue().toString());
            lblPrecoTot.setText(String.format("%.2f", precoTot));
            spnQtd.setValue(1);
            txtCodProduto.setText("");
        }else{
            JOptionPane.showMessageDialog(null, "Produto não encontrado!", "Erro",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btncadastroProdActionPerformed

    private void btnFinalizarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarVendaActionPerformed
        TelaRequestCliente trc = new TelaRequestCliente();
        ArrayList<Integer> qtds = new ArrayList<>();
        for(int i = 0; i < pVenda.size(); i++){
            qtds.add(i,0);
        }
        for(int i = 0; i < tblProdutos.getRowCount(); i++){
            
            int codProduto = Integer.parseInt(tblProdutos.getValueAt(i, 0).toString());
            int qtdProdutosNaColunaQtd = Integer.parseInt(tblProdutos.getValueAt(i, 3).toString());
            int pos = pVenda.indexOf(controleProduto.pesquisaProdutoCod(codProduto))+1;
            System.out.println(pos);
            int qtdTot = qtds.get(pos)+qtdProdutosNaColunaQtd;
            qtds.add(pos, qtdTot);
//           int valorTabela = Integer.parseInt(model.getValueAt(i, 3).toString());
//           Produto p = pVenda.get(i);
//   
//            qtds.add(pVenda.indexOf(p), qtds.get(pVenda.indexOf(p))+valorTabela);
        }
        System.out.println(qtds.size());
        Date d = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        Venda v = new Venda(precoTot, Integer.parseInt(txtCodVenda.getText()), trc.getCliente(), pVenda,
                qtds, sdf.format(d.getTime()), TelaLogin.getFuncionarioLogado());
        trc.dispose();
        
        Object[] options = { "Finalizar", "Cancelar" };
        int opc = JOptionPane.showOptionDialog(null, "Finalizar compra?", "Confirmação", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[0]);
        
        if(opc == JOptionPane.OK_OPTION){
               if(controleVenda.cadastraVenda(v, qtds)){
                   JOptionPane.showMessageDialog(null, "Venda finalizada com sucesso!", "Venda finalizada",JOptionPane.INFORMATION_MESSAGE);
                   lblPrecoTot.setText("00.00");
                   txtCodProduto.setText("");
                   int id = Integer.parseInt(idVenda);
                   id++;
                   txtCodVenda.setText(String.valueOf(id));
                   this.resetTable();
                   precoTot = 0;
               }
        }
    }//GEN-LAST:event_btnFinalizarVendaActionPerformed

    private void tblProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProdutosMouseClicked
        int selectedRow = tblProdutos.getSelectedRow();
        String id = tblProdutos.getValueAt(selectedRow, 0).toString();
        String qtd = tblProdutos.getValueAt(selectedRow, 3).toString();
        
        txtCodProduto.setText(id);
        spnQtd.setValue(Integer.parseInt(qtd));
    }//GEN-LAST:event_tblProdutosMouseClicked

    private void btnEditarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarProdActionPerformed
        try{
        int selectedRow = tblProdutos.getSelectedRow();
        int qtdN = Integer.parseInt(spnQtd.getModel().getValue().toString());
        int qtdtabela = Integer.parseInt(tblProdutos.getValueAt(selectedRow, 3).toString());
        double precUn = Double.parseDouble(tblProdutos.getValueAt(selectedRow, 2).toString());
        //String precTos = lblPrecoTot.getText().replace(",", ".");
        double precTo = Double.parseDouble(lblPrecoTot.getText().replaceAll("\\,", "."));
        double precLblNovo = precTo - precUn*qtdtabela;
        precLblNovo += precUn*qtdN;
        precoTot = precLblNovo;
        
        model.setValueAt(String.valueOf(qtdN), selectedRow, 3);
        model.setValueAt(String.valueOf(precUn*qtdN), selectedRow, 4);
        lblPrecoTot.setText(String.format("%.2f", precoTot));
        model.fireTableDataChanged();
        }catch(ArrayIndexOutOfBoundsException e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnEditarProdActionPerformed

    private void btnExcluirProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirProdActionPerformed
        int selectedRow = tblProdutos.getSelectedRow();
        int qtdtabela = Integer.parseInt(tblProdutos.getValueAt(selectedRow, 3).toString());
        double precUn = Double.parseDouble(tblProdutos.getValueAt(selectedRow, 2).toString());
        double precTo = Double.parseDouble(lblPrecoTot.getText().replaceAll("\\,", "."));
        double precLblNovo = precTo - precUn*qtdtabela;
        precoTot = precLblNovo;
        
        lblPrecoTot.setText(String.format("%.2f", precoTot));
        
        model.getDataVector().removeElementAt(selectedRow);
        pVenda.remove(selectedRow);
        model.fireTableDataChanged();
    }//GEN-LAST:event_btnExcluirProdActionPerformed

    private void btnListarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarProdActionPerformed
        new TelaProduto().setVisible(true);
    }//GEN-LAST:event_btnListarProdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaVenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditarProd;
    private javax.swing.JButton btnExcluirProd;
    private javax.swing.JButton btnFinalizarVenda;
    private javax.swing.JButton btnListarProd;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JButton btncadastroProd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPrecoTot;
    private javax.swing.JSpinner spnQtd;
    private javax.swing.JTable tblProdutos;
    private javax.swing.JTextField txtCodProduto;
    private javax.swing.JTextField txtCodVenda;
    // End of variables declaration//GEN-END:variables
}
